apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
        - name: healthcare-app
          image: bindukantharaju/healthcare-app:v1
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
spec:
  selector:
    app: healthcare
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: LoadBalancer

