apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app
  labels:
    app: healthcare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
        - name: healthcare-container
          image: bindukantharaju/healthcare-app:v1
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
spec:
  selector:
    app: healthcare
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082

